keys:
  - &shikanime age1pwl9yz4k4255a4h8qz7lafce8wxhsul0cnqwmr8528fqgujlfshshv3z3g
creation_rules:
  - path_regex: secrets/shikanime\.enc\.yaml$
    key_groups:
      - age:
          - *shikanime
  - path_regex: secrets/gouv\.enc\.yaml$
    key_groups:
      - age:
          - *shikanime
  - path_regex: secrets/operator6o\.enc\.yaml$
    key_groups:
      - age:
          - *shikanime
